# Generated by Django 5.2.8 on 2025-11-09 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('sponsor_id', models.IntegerField()),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'legislators',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.bill')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vote_type', models.IntegerField()),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.legislator')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.vote')),
            ],
            options={
                'db_table': 'vote_results',
            },
        ),
    ]
